flowchart TD
    aa{{MenorTPI}} --> if0{"TPI < TPE && TPI < TPQA && TPI < TPEM && TPI < TPD && TPI < TPM && TPI < TPRE"}
    if0 --> |si| a[bool = true]
    if0 --> |no| a1[bool = false]

%% TODOS los menor EsMenorTPx es lo mismo  

