flowchart TD
    aa{{EsLlegadaMenor}} --> if0{"TPLL < TPI && TPLL < TPE && TPLL < TPQA && TPLL < TPEm && TPLL < TPD && TPLL < TPM"}
    if0 --> |si| a[bool = true]
    if0 --> |no| a1[bool = false]

%% TODOS los menor EsMenorTPx es lo mismo  
