flowchart TD    
    direction TD
    subgraph Init
    CI[[CI]] --> Impresion{{Menor TPI}} --> Encuadernacion{{Menor TPE}} --> QA{{Menor TPQA}} --> Embalaje{{Menor TPEm}} --> Desperfecto{{Menor TPD}} --> Mantenimiento{{Menor TPM}}
    end
    
    subgraph Eleccion de Evento 
    direction TD
    Init{{Init}} --> MenorLlegada{{EsLlegadaMenor}}
    MenorLlegada ==> if{bool = true}
    if --> |si| Llegada{{LlegadaPedido}}
    if --> |no| EsImpresionMenor{{EsImpresionMenor}}
    EsImpresionMenor --> if2{bool = true}
    if2 --> |si| Impresion2{{Impresion}}
    if2 --> |no| EsEncuadernadoMenor{{EsEncuadernadoMenor}}
    EsEncuadernadoMenor --> if3{bool = true}
    if3 --> |si| Encuadernacion2{{Encuadernacion}}
    if3 --> |no| EsQAMenor{{EsQAMenor}}
    EsQAMenor --> if4{bool = true}
    if4 --> |si| QA2{{QA}}
    if4 --> |no| EsEmbalajeMenor{{EsEmbalajeMenor}}
    EsEmbalajeMenor --> if5{bool = true}
    if5 --> |si| Embalaje2{{Embalaje}}
    if5 --> |no| EsDesperfectoMenor{{EsDesperfectoMenor}}
    EsDesperfectoMenor --> if7{bool = true}
    if7 --> |si| Desperfecto2{{"Desperfecto[i_des][j_des]"}} --> fin
    if7 --> |no| Mantenimiento2{{"Mantenimiento[i_man][j_man]"}} --> fin((fin))
    end
