flowchart TD
    aa{{MenorTPMA}} --> ii[i = 0] --> tpm[TPM = HV] --> ifi{"i < 3"}
    ifi --> |si| jj[j = 0] --> ifj{"j < CM[i]"}
    ifj --> |si| if1{"TPM >= TPM[i][j]"} 
    if1 --> |si| a1["TPM = TPM[i][j]"] --> a2[i_man = i] --> a3[j_man = j] --> cc[j ++] --> ifj
    if1 --> |no| cc
    ifj --> |no| icc[i ++] --> ifi
    ifi --> |no| a4((fin))

