flowchart TD
    direction TB
    
    %% tpi ya es el menor tpi[]
    a[T = TPM] --> a11["CantMan ++"] --> b{{ID}} %% Tiempo mantenimiento programado
    b --> c["TPM[i_man][j_man] = T + IM"] --> c1{"TPD[i_man][j_man] >= TPM[i_man][j_man]"}
    c1 -->|no| lal[DesEv ++]
    lal --> d["TPD[i_man][j_man] = T + ID TR[i_man] += DM"]
    c1 -->|si| d
    d --> e{i_man}
    e -->|0| f["TPI[j_man] += DM"]
    e -->|1| f1["TPE[j_man] += DM"]
    e -->|2| f2["TPEm[j_man] += DM"]
    f --> g["$TM += $M[i_man]; SAM"]
    f1 --> g
    f2 --> g
    g --> p((fin))