flowchart TD
a0{{EncontrarMejorEncuadernadora}} --> if{ALG}
if --> |POR_CONFIGURACION| a2["indice = CLM[1].index(min(filter(lambda lote: lote.config==CxM[1][i_enc].lote.conf, CLM[1]), key=lambda lote: lote.ts))"]
if --> |PRIORIDADES| a3["indice = CLM[1].index(min(filter(lambda lote: lote.config==CONFIG_PRIORITARIA, CLM[1]), key=lambda lote: lote.ts))"]
if --> |FIFO| a1{indice == null}
a1 --> |si| b["indice = CLM[1].index(min(CLM[1], key=lambda lote: lote.ts))"]
a1 --> |no| g
a2 --> a1
a3 --> a1
b --> g{"CxM[1][i_enc].lote.conf == CLM[1][indice].conf"}
g --> |si| g1[TConf = 0]
g --> |no| g2{{TConf}}
g2 --> g3["CxM[1][i_enc].lote.conf = CLM[1][indice].conf"] --> g4 
g1 --> g4((fin)) 