flowchart TD
    direction TD
    
    %% tpi ya es el menor tpi[]
    %%a[T = TPI] --> if{¿Hay Lote en Cola Impresion?} %% esto chequea stock tambien
    a[T = TPI] --> if{"CLM[0].size() > 0 && SD[0] > 0"} %% esto chequea stock tambien
    subgraph Generar nueva impresion
    if --> |si| e{{"Sacar de la cola de impresion"}} --> s{{DI}} --> b["TPI[i_imp] = T + DI + TConf"] --> l
    if --> |no| l[" "]
    end
    subgraph Generar encaudernacion
    l --> g{{Encontrar encuadernasion libre}} --> if2{puede_encuadernar}
    if2 --> |si| aaa{{DE}} --> h["TPE[i_enc] = T + DE + TConf"] --> ll[" "]
    if2 --> |no| aa{{Agregar a cola encuadernacion}}  --> ll
    end
    subgraph Reponer stock
    ll --> if3{"SD[0] <= SPR[0]"}
    if3 --> |si| r{{"Reposicion(0)"}}
    end