flowchart TD
    direction TD
    
    a[T = TPI] --> lote["lote = CxM[0][i_imp].lote"]
   
    subgraph Generar encuadernacion
    lote --> g{{Encontrar mejor encuadernadora}} --> if2{"i_enc != null"}
    if2 --> |si| aaa0["CxM[1][i_enc].lote = lote; CxM[1][i_enc].config = lote.config"] --> aaa{{DE}} --> ii1{"TPE[i_enc] = HV"} --> |si| ii2["FTO[1] += T; InicioOcio[1][i_enc] = HV"] --> hh
    ii1 --> |no| hh["TPE[i_enc] = T + DE + TConf"] --> ll
    if2 --> |no| z9["lote.ts = T"] --> aa["CLM[1].push(lote)"]  --> ll 
    end
   
    subgraph Generar nueva impresion
    ll[" "] --> if
    if{"CLM[0].size() > 0"} --> |si| e{{"Sacar de la cola de impresion"}} --> s{{DI}} --> i1{"TPI[i_imp] = HV"} --> |si| i2["FTO[0] += T; InicioOcio[0][i_imp] = HV"] --> i
    i1 --> |no| i["TPI[i_imp] = T + DI + TConf"] --> l[" "]
    if --> |no| zz["TPI[i_imp] = HV; ITO[0] += T; InicioOcio[0][i_imp] = T"] --> l
    end

    l --> fin(("fin"))
