flowchart TD
    aa{{DE}} --> a{{R}}
    a --> a1["DE = DuracionEncuadernacion(R)"]
    a1 --> a4["HoraDia = Mod(T,1440)/60"]
    a4 --> a9["TAdicional = 0"]
    a9 --> a2{"HoraDia > InicioCaro && HoraDia <= FinCaro"}
    a2 --> |si| a3{"PEFC == true"} %% Producimo en franja cara
    a3 --> |no| b2["TAdicional = (FinCaro - HoraDia) x 60; CostoAhorradoPorTCaro[0] += CTC/m x TAdicional"]
    a3 --> |si| a5["CTE += CTC/m x (FinCaro - T) + CTN/m * DI - (FinCar - T)"] --> d %% costo tiempo de produccion caro
    a2 --> |no| a6["CTE += CTN/m x DI"] --> d
    b2 --> c[DE += TAdicional]
    c --> d((Fin))
