flowchart TD
    direction TD

    a[T = TPE] --> if{"CLM[1].size() > 0 && SD[1] > 0"}
    subgraph Generar nueva encuadernacion
    if --> |si| e{{"Sacar de la cola de encuadernacion"}} --> s{{DE}} --> b["TPE[i_enc] = T + DE + TConf"] --> l
    if --> |no| zz["TPE[i_enc] = HV"] --> l[" "]
    end
    subgraph Generar QA
    l --> g{{Encontrar mejor QA}} --> if2{puede_QAar}
    if2 --> |si| aaa{{DQA}} --> h["TPQA[i_qa] = T + DQA"] --> ll[" "]
    if2 --> |no| aa{{Agregar a cola QA}}  --> ll
    end
    subgraph Reponer stock
    ll --> if3{"SD[1] <= SPR[1]"}
    if3 --> |si| r{{"Reposicion(1)"}}
    end
