flowchart TD
a0{{SacarDeLaColaDeEncuadernacion}} --> if{ALG}
if --> |POR_CONFIGURACION| a2["indice = index_or_null(min(filter(lambda lote: lote.conf == CxM[1][i_enc].lote.conf, CLM[1]), key=lambda lote: lote.ts))"]
if --> |PRIORIDADES| a3["indice = index_or_null(min(filter(lambda lote: lote.conf == CONFIG_PRIORITARIA, CLM[1]), key=lambda lote: lote.ts))"]
if --> |FIFO| a1["indice = null"]
a2 --> a4
a3 --> a4
a1 --> a4{"indice == null"}
a4 --> |si| b["indice = CLM[1].index(min(CLM[1], key=lambda lote: lote.ts))"]
a4 --> |no| g
b --> g{"CxM[1][i_enc].conf == CLM[1][indice].conf"}
g --> |si| g1[TConf = 0]
g --> |no| g2{{TConf}}
g1 --> g3["CxM[1][i_enc].lote = CLM[1][indice]"]
g2 --> g3
g3 --> g4["CLM[1].pop(indice)"] --> g5((fin))
