flowchart TD
    direction TD

    a[T = TPQA] --> lote["lote = CxM[2][i_qa].lote"]

    subgraph Imprimir si salio mal el QA
    lote --> defecto{"lote.defectuoso"}
    defecto --> |si| bb{{AQA}}
    bb --> bb1{"AQA < PQA"}
    bb1 --> |si| lol["CantLotesReProcesados ++"] --> e1{{Encontrar mejor impresora}} --> f1{"i_imp != null"}
    f1 --> |si| aimp["CxM[0][i_imp].lote = lote; CxM[0][i_imp].config = lote.config"] --> g1{{DI}} --> ii1{"TPI[i_imp] == HV"} --> |si| ii2["FTO[0] += T; InicioOcio[0][i_imp] = HV"] --> ii9
    ii1 --> |no| ii9["TPI[i_imp] = T + DI + TConf"] --> z[" "]
    f1 --> |no| z9["lote.ts = T"] --> h1["CLM[0].push(lote)"] --> z
    end

    subgraph Generar embalaje
    defecto --> |no| g{{Encontrar mejor embaladora}}
    bb1 --> |no| escape["CantLotesDefectuososNoDetectados ++"] --> g
    g --> if2{"i_emb != null"}
    if2 --> |si| aemb["CxM[3][i_emb].lote = lote; CxM[3][i_emb].config = lote.config"] --> aaa{{DEm}} --> iaa1{"TPEm[i_emb] == HV"} --> |si| iaa2["FTO[3] += T; InicioOcio[3][i_emb] = HV"] --> hhh
    iaa1 --> |no| hhh["TPEm[i_emb] = T + DEm + TConf"] --> z
    if2 --> |no| z99["lote.ts = T"] --> aa["CLM[3].push(lote)"]  --> z
    end

    subgraph Generar nuevo QA
    z --> if{"CLM[2].size() > 0"}
    if --> |si| e{{"Sacar de la cola de QA"}} --> s{{DQA}} --> i1{"TPQA[i_qa] == HV"} --> |si| i2["FTO[2] += T; InicioOcio[2][i_qa] = HV"] --> b
    i1 --> |no| b["TPQA[i_qa] = T + DQA"] --> l[" "]
    if --> |no| zz["TPQA[i_qa] = HV; ITO[2] += T; InicioOcio[2][i_qa] = T"] --> l
    end

    l --> fin((fin))
