flowchart TD
    direction TD
    a[T = TPLL] --> b{{IA}} --> c[TPLL = T + IA] --> d0{{TipoConfig}} --> d{{CantLotes}}
    d --> d1[CTP ++] --> d2[CTL += CantLotes] --> d3["TTIP += T * CantLotes"] --> bb[j = 0]
    bb --> iff{"j < CantLotes"}
    iff --> |si| cc[j ++] --> lote["lote = new Lote(config = TipoConfig)"] --> z1{{Encontrar mejor impresora}} --> f{"i_imp != null"}
    iff --> |no| fin((FIN))
    f --> |si| z2["CxM[0][i_imp].lote = lote; ; CxM[0][i_imp].config = lote.config"] --> g{{DI}} --> i1{"TPI[i_imp] = HV"} --> |si| i2["FTO[0] += T"] --> i
    i1 --> |no| i["TPI[i_imp] = T + DI + TConf"]
    --> j[" "]
    f --> |no| z9["lote.ts = T"] --> h["CLM[0].push(lote)"]
    
    h --> j --> iff
    
