flowchart TD
    direction TD

    z{{"ActualizarStock[i]"}} --> b["T = TPRep[i]"] --> c["SD[i] += SAR[i]"] --> d{i}

    d --> |0| imp0["j = 0"]
    d --> |1| enc0["j = 0"]
    d --> |2| emb0["j = 0"]
    d --> |otro| repo

    subgraph Actualizar stock de impresion
    imp0 --> imp_if{"j < CM[0] && CLM[0].size() > 0 && SD[0] > 0"}
    imp_if --> |si| imp_hv{"TPI[j] == HV"}
    imp_hv --> |si| imp_idx["i_imp = j"] --> imp_cola{{"Sacar de la cola de impresion"}} --> imp_di{{DI}} --> imp_stock["SD[0] -= 1; $TRep += $MP[0]"] --> imp_fto["FTO[0] += T"] --> imp_tpi["TPI[i_imp] = T + DI + TConf"] --> imp_next["j ++"] --> imp_if
    imp_hv --> |no| imp_next
    imp_if --> |no| repo
    end

    subgraph Actualizar stock de encuadernacion
    enc0 --> enc_if{"j < CM[1] && CLM[1].size() > 0 && SD[1] > 0"}
    enc_if --> |si| enc_hv{"TPE[j] == HV"}
    enc_hv --> |si| enc_idx["i_enc = j"] --> enc_cola{{"Sacar de la cola de encuadernacion"}} --> enc_de{{DE}} --> enc_stock["SD[1] -= 1; $TRep += $MP[1]"] --> enc_fto["FTO[1] += T"] --> enc_tpe["TPE[i_enc] = T + DE + TConf"] --> enc_next["j ++"] --> enc_if
    enc_hv --> |no| enc_next
    enc_if --> |no| repo
    end

    subgraph Actualizar stock de embalaje
    emb0 --> emb_if{"j < CM[3] && CLM[3].size() > 0 && SD[2] > 0"}
    emb_if --> |si| emb_hv{"TPEm[j] == HV"}
    emb_hv --> |si| emb_idx["i_emb = j"] --> emb_cola{{"Sacar de la cola de embalaje"}} --> emb_dem{{DEm}} --> emb_stock["SD[2] -= 1; $TRep += $MP[2]"] --> emb_fto["FTO[3] += T"] --> emb_tpem["TPEm[i_emb] = T + DEm + TConf"] --> emb_next["j ++"] --> emb_if
    emb_hv --> |no| emb_next
    emb_if --> |no| repo
    end

    repo{"SD[i] <= SPR[i]"}
    repo --> |si| tr{{TR}} --> nueva_repo["TPRep[i] = T + TR"] --> fin((fin))
    repo --> |no| sin_repo["TPRep[i] = HV"] --> fin
