flowchart TD
    a1[[CI]] --> a2
    a2["
        CTP = 0
        CTL = 0
        $TM = 0
        CantMan = 0
        DesEv = 0
        TTIP = 0
        TTFP = 0
        STPL = 0
        CTLFin = 0
        STPP = 0
        CTPFin = 0
        pedido_id_actual = 0
        Pedidos = {}
        ITO = {0,0,0,0}
        FTO = {0,0,0,0}
        InicioOcio[etapa][maquina] = 0 para toda maquina productiva
        TiempoParadoEtapa = {0,0,0,0}
        TiempoCaroEvitado = {0,0,0,0}
    "]

    %% TODO: definir config inicial por defecto para cada maquina.
    %% Ejemplo: CxM[etapa][maquina].lote.conf = CONF_DEFAULT.
