flowchart TD
    a1[[CI]] --> a2
    a2["
        ITO = {0,0,0,0},
    "]

    %% TODO: definir config inicial por defecto para cada maquina.
    %% Ejemplo: CxM[etapa][maquina].lote.conf = CONF_DEFAULT.
