flowchart TD
    a1[[CI]] --> a2
    a2["
        SI[3] = {10,10,10}; 
        $SI = SI[0].$MP[0] + SI[1].$MP[1] + SI[2].$MP[2]
        
    "]

    %% TODO: definir config inicial por defecto para cada maquina.
    %% Ejemplo: CxM[etapa][maquina].lote.conf = CONF_DEFAULT.
