flowchart TD
    direction TD
    
    %% tpi ya es el menor tpi[]
    a[T = TPEm] --> if{¿Hay Lote en Cola embalaje?} %% esto chequea stock tambien
    subgraph Generar nuevo QA
    if --> |si| e{{"Sacar de la cola de embalaje"}} --> s{{DEm}} --> b["TPEm[i_emb] = T + DEm + TConf"] --> l
    if --> |no| l[" "]
    end
    subgraph Reponer stock
    l --> if3{"SD[2] <= SPR[2]"}
    if3 --> |si| r{{"Reposicion(2)"}}
    end