flowchart TD
    direction TD
    a[T = TPLL] --> b{{IA}} --> c[TPLL = T + IA] --> d{{Cant Lotes}}
    d{{Cant Lotes}} --> bb[j = 0]
    bb --> if2{"j < CM[0]"}
    if2 --> cc[j ++]
    %%Manejo de stock en encontrar maquina impresión libre 
    cc --> |si| e{{Encontrar Impresora Libre}} --> f{puede_imprimir} 
    f --> |si| g{{DI}} --> i["TPI[i] = T + DI + TConf"]
    f --> |no| h{{Agregar lote a cola}}
    h --> j[" "]
    i --> j
    j --> if2