flowchart TD
    direction TD
    
    %% tpi ya es el menor tpi[]
    a[T = TPM] --> b{{ID}} %% Tiempo mantenimiento programado 
    b --> c["TPD[i_man][j_man] = T + ID"]
    c --> d["TPM[i_man][j_man] = T + IM"]
    d --> e{i_man}
    e --> |0| f["TPI[j_man] += DM"]
    e --> |1| f1["TPE[j_man] += DM"]
    e --> |2| f2["TPEm[j_man] += DM"]
    f --> g((fin))
    f1 --> g
    f2 --> g
     