flowchart TD
    direction TD
    
    %% tpi ya es el menor tpi[]
    a[T = TPQA] --> if{¿Hay Lote en Cola QA?} %% esto chequea stock tambien
    subgraph Generar nuevo QA
    if --> |si| e{{"Sacar de la cola de QA"}} --> s{{DQA}} --> b["TPQA[i_qa] = T + DQA + TConf"] --> l
    if --> |no| l[" "]
    end
    subgraph Imprimir si salio mal el QA
    l --> bb{{AQA}} %% AQA
    bb --> bb1{PQA < AQA}
    bb1 --> |si| e1{{Encontrar Maquina Impresion Libre}} --> f1{puede_imprimir} 
    f1 --> |si| g1{{DI}} --> i["TPI[i] = T + DI + TConf"]
    f1 --> |no| h1{{Agregar lote a cola}}
    i --> z[" "]
    h1 --> z
    end
    subgraph Generar embalaje
    bb1 --> |no| g
    g{{Encontrar embalaje libre}} --> if2{puede_embalajear}
    if2 --> |si| aaa{{DEm}} --> h["TPEm[i_emb] = T + DEm + TConf"] --> ll[" "]
    if2 --> |no| aa{{Agregar a cola Emabalaje}}  --> ll
    end
