flowchart TD
    direction TD

    a[T = TPQA] --> lote["lote = CxM[2][i_qa].lote"]

    subgraph Imprimir si salio mal el QA
    lote --> bb{{AQA}}
    bb --> bb1{"PQA < AQA"}
    bb1 --> |si| e1{{Encontrar mejor impresora}} --> f1{"i_imp != null"}
    f1 --> |si| aimp["CxM[0][i_imp].lote = lote; CxM[0][i_imp].config = lote.config"] --> g1{{DI}} --> s0["SD[0] -= 1; $TRep += $MP[0]"] --> i["TPI[i_imp] = T + DI + TConf"] --> z[" "]
    f1 --> |no| z9["lote.ts = T"] --> h1["CLM[0].push(lote)"] --> z
    end

    subgraph Generar embalaje
    bb1 --> |no| g{{Encontrar mejor embaladora}} --> if2{"i_emb != null"}
    if2 --> |si| aemb["CxM[3][i_emb].lote = lote; CxM[0][i_emb].config = lote.config"] --> aaa{{DEm}} --> s2["sd[2] -= 1;  $TRep += $MP[2]"] --> h["TPEm[i_emb] = T + DEm + TConf"] --> z
    if2 --> |no| z99["lote.ts = T"] --> aa["CLM[3].push(lote)"]  --> z
    end

    subgraph Generar nuevo QA
    z --> if{"CLM[2].size() > 0"}
    if --> |si| e{{"Sacar de la cola de QA"}} --> s{{DQA}} --> b["TPQA[i_qa] = T + DQA"] --> l[" "]
    if --> |no| zz["TPQA[i_qa] = HV"] --> l
    end

    subgraph Reponer stock
    l --> if3{"SD[0] <= SPR[0]"}
    if3 --> |si| r0{{"Reposicion(0)"}} --> if4{"SD[2] <= SPR[2]"}
    if3 --> |no| if4
    if4 --> |si| r2{{"Reposicion(2)"}} --> fin((fin))
    if4 --> |no| fin
    end
